FROM golang:1.16 as build
WORKDIR /go/src/app
COPY . /go/src/app
RUN cd bot && \
    GOOS=linux go build -o /gentei-bot .

FROM gcr.io/distroless/base
COPY --from=build /gentei-bot /gentei-bot
ENTRYPOINT [ "/gentei-bot" ]