FROM golang:1.16 as build
WORKDIR /go/src/app
COPY . /go/src/app
RUN cd jobs/member-check && \
    GOOS=linux go build -o /gentei-member-check .

FROM gcr.io/distroless/base
COPY --from=build /gentei-member-check /gentei-member-check
ENTRYPOINT [ "/gentei-member-check" ]