// Code generated by entc, DO NOT EDIT.

package youtubetalent

import (
	"time"
)

const (
	// Label holds the string label denoting the youtubetalent type in the database.
	Label = "you_tube_talent"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChannelName holds the string denoting the channel_name field in the database.
	FieldChannelName = "channel_name"
	// FieldThumbnailURL holds the string denoting the thumbnail_url field in the database.
	FieldThumbnailURL = "thumbnail_url"
	// FieldMembershipVideoID holds the string denoting the membership_video_id field in the database.
	FieldMembershipVideoID = "membership_video_id"
	// FieldLastMembershipVideoIDMiss holds the string denoting the last_membership_video_id_miss field in the database.
	FieldLastMembershipVideoIDMiss = "last_membership_video_id_miss"
	// FieldLastUpdated holds the string denoting the last_updated field in the database.
	FieldLastUpdated = "last_updated"
	// EdgeGuilds holds the string denoting the guilds edge name in mutations.
	EdgeGuilds = "guilds"
	// EdgeMembers holds the string denoting the members edge name in mutations.
	EdgeMembers = "members"
	// Table holds the table name of the youtubetalent in the database.
	Table = "you_tube_talents"
	// GuildsTable is the table that holds the guilds relation/edge. The primary key declared below.
	GuildsTable = "you_tube_talent_guilds"
	// GuildsInverseTable is the table name for the Guild entity.
	// It exists in this package in order to avoid circular dependency with the "guild" package.
	GuildsInverseTable = "guilds"
	// MembersTable is the table that holds the members relation/edge. The primary key declared below.
	MembersTable = "user_youtube_memberships"
	// MembersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	MembersInverseTable = "users"
)

// Columns holds all SQL columns for youtubetalent fields.
var Columns = []string{
	FieldID,
	FieldChannelName,
	FieldThumbnailURL,
	FieldMembershipVideoID,
	FieldLastMembershipVideoIDMiss,
	FieldLastUpdated,
}

var (
	// GuildsPrimaryKey and GuildsColumn2 are the table columns denoting the
	// primary key for the guilds relation (M2M).
	GuildsPrimaryKey = []string{"you_tube_talent_id", "guild_id"}
	// MembersPrimaryKey and MembersColumn2 are the table columns denoting the
	// primary key for the members relation (M2M).
	MembersPrimaryKey = []string{"user_id", "you_tube_talent_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLastUpdated holds the default value on creation for the "last_updated" field.
	DefaultLastUpdated func() time.Time
)
