// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Guild is the predicate function for guild builders.
type Guild func(*sql.Selector)

// GuildRole is the predicate function for guildrole builders.
type GuildRole func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserMembership is the predicate function for usermembership builders.
type UserMembership func(*sql.Selector)

// YouTubeTalent is the predicate function for youtubetalent builders.
type YouTubeTalent func(*sql.Selector)
