// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/member-gentei/member-gentei/gentei/ent/predicate"
	"github.com/member-gentei/member-gentei/gentei/ent/youtubetalent"
)

// YouTubeTalentDelete is the builder for deleting a YouTubeTalent entity.
type YouTubeTalentDelete struct {
	config
	hooks    []Hook
	mutation *YouTubeTalentMutation
}

// Where appends a list predicates to the YouTubeTalentDelete builder.
func (yttd *YouTubeTalentDelete) Where(ps ...predicate.YouTubeTalent) *YouTubeTalentDelete {
	yttd.mutation.Where(ps...)
	return yttd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (yttd *YouTubeTalentDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(yttd.hooks) == 0 {
		affected, err = yttd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*YouTubeTalentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			yttd.mutation = mutation
			affected, err = yttd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(yttd.hooks) - 1; i >= 0; i-- {
			if yttd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = yttd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, yttd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (yttd *YouTubeTalentDelete) ExecX(ctx context.Context) int {
	n, err := yttd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (yttd *YouTubeTalentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: youtubetalent.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: youtubetalent.FieldID,
			},
		},
	}
	if ps := yttd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, yttd.driver, _spec)
}

// YouTubeTalentDeleteOne is the builder for deleting a single YouTubeTalent entity.
type YouTubeTalentDeleteOne struct {
	yttd *YouTubeTalentDelete
}

// Exec executes the deletion query.
func (yttdo *YouTubeTalentDeleteOne) Exec(ctx context.Context) error {
	n, err := yttdo.yttd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{youtubetalent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (yttdo *YouTubeTalentDeleteOne) ExecX(ctx context.Context) {
	yttdo.yttd.ExecX(ctx)
}
