name: Build and push Docker images
on:
  push:
    branches: [master]

jobs:
  build-bot:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push bot:latest, bot:commit
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.bot
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/bot:latest
            ghcr.io/${{ github.repository }}/bot:${{ github.sha }}
  build-member-check:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push member-check:latest, member-check:commit
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.member-check
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/member-check:latest
            ghcr.io/${{ github.repository }}/member-check:${{ github.sha }}