name: prod

on:
  push:
    branches:
      - "main"

defaults:
  run:
    working-directory: gentei

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker build + tag
        env:
          DOCKER_BUILDKIT: "1"
        run: |
          docker build . -t gentei
          docker tag gentei ghcr.io/member-gentei/gentei:${{ github.sha }}
          docker tag gentei ghcr.io/member-gentei/gentei:latest
      - name: docker push
        run: |
          docker push ghcr.io/member-gentei/gentei:${{ github.sha }}
          docker push ghcr.io/member-gentei/gentei:latest
  deploy:
    needs: docker
    runs-on: self-hosted
    defaults:
      run:
        working-directory: gentei/_k8s
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3.0
      - uses: imranismail/setup-kustomize@v1
      - name: kustomize
        run: |
          kustomize edit set image ghcr.io/member-gentei/gentei=ghcr.io/member-gentei/gentei:${{ github.sha }}
      - run: kubectl -n gentei apply -k .
